var fs = require('fs');
var path = 'c:\\Users\\q\\Desktop\\my\\script.js';
var content = fs.readFileSync(path, 'utf8');
var lines = content.split(/\r?\n/);

var startIdx = 1434 - 1;
var endIdx = 1874 - 1;

console.log('Line ' + (startIdx + 1) + ': ' + lines[startIdx]);
console.log('Line ' + (endIdx + 1) + ': ' + lines[endIdx]);

var newFunc = [
'    function playPlanetCollision() {',
'      return new Promise(function (resolve) {',
'        // ============ 初始化 ============',
'        collisionPlaying = true;',
'        collisionOverlay.classList.add(\'active\');',
'        collisionOverlay.setAttribute(\'aria-hidden\', \'false\');',
'',
'        if (collisionCaption) {',
'          collisionCaption.textContent = \'星域共振中……\';',
'          collisionCaption._successShown = false;',
'        }',
'',
'        const canvas = collisionCanvas;',
'        if (!canvas) {',
'          setTimeout(function () {',
'            collisionOverlay.classList.remove(\'active\');',
'            collisionPlaying = false;',
'            resolve();',
'          }, 300);',
'          return;',
'        }',
'',
'        const ctx = canvas.getContext(\'2d\');',
'        let animId = null;',
'        canvas.width = window.innerWidth;',
'        canvas.height = window.innerHeight;',
'',
'        const DURATION = 3200;',
'        const startTime = performance.now();',
'        const cx = canvas.width / 2;',
'        const cy = canvas.height / 2;',
'',
'        // 颜色：柔和蓝紫系',
'        const colA = { r: 120, g: 140, b: 230 };',
'        const colB = { r: 160, g: 130, b: 235 };',
'        function rgba(c, a) {',
'          return \'rgba(\' + c.r + \',\' + c.g + \',\' + c.b + \',\' + a + \')\';',
'        }',
'',
'        // 背景星星（60 粒，足够）',
'        const bgStars = [];',
'        for (let i = 0; i < 60; i++) {',
'          bgStars.push({',
'            x: Math.random() * canvas.width,',
'            y: Math.random() * canvas.height,',
'            size: Math.random() * 1.2 + 0.3,',
'            phase: Math.random() * Math.PI * 2,',
'            alpha: 0.3 + Math.random() * 0.5',
'          });',
'        }',
'',
'        // ============ 粒子池（在撞击时一次性生成） ============',
'        let particles = [];',
'        let hasImpactFired = false;',
'',
'        function spawnImpactBurst() {',
'          // 碎片 40 粒（快速扩散带重力）',
'          for (let i = 0; i < 40; i++) {',
'            const angle = Math.random() * Math.PI * 2;',
'            const speed = 2 + Math.random() * 8;',
'            particles.push({',
'              type: \'debris\',',
'              x: cx, y: cy,',
'              vx: Math.cos(angle) * speed,',
'              vy: Math.sin(angle) * speed,',
'              life: 1, decay: 0.012 + Math.random() * 0.02,',
'              size: 1.5 + Math.random() * 2.5,',
'              color: Math.random() < 0.5 ? colA : colB',
'            });',
'          }',
'          // 成滩星星 80 粒（慢速，带闪烁）',
'          for (let i = 0; i < 80; i++) {',
'            const angle = Math.random() * Math.PI * 2;',
'            const speed = 0.8 + Math.random() * 3;',
'            particles.push({',
'              type: \'star\',',
'              x: cx + (Math.random() - 0.5) * 12,',
'              y: cy + (Math.random() - 0.5) * 12,',
'              vx: Math.cos(angle) * speed,',
'              vy: Math.sin(angle) * speed,',
'              life: 1, decay: 0.0015 + Math.random() * 0.0015,',
'              size: 1.2 + Math.random() * 1.8,',
'              color: Math.random() < 0.5 ? colA : colB,',
'              twinkle: Math.random() * Math.PI * 2',
'            });',
'          }',
'          // 十字闪光亮点 30 粒',
'          for (let i = 0; i < 30; i++) {',
'            const angle = Math.random() * Math.PI * 2;',
'            const speed = 3 + Math.random() * 10;',
'            particles.push({',
'              type: \'sparkle\',',
'              x: cx, y: cy,',
'              vx: Math.cos(angle) * speed,',
'              vy: Math.sin(angle) * speed,',
'              life: 1, decay: 0.03 + Math.random() * 0.03,',
'              size: 1 + Math.random() * 1.5',
'            });',
'          }',
'          // 旋转碎片 20 粒',
'          for (let i = 0; i < 20; i++) {',
'            const angle = Math.random() * Math.PI * 2;',
'            const speed = 2 + Math.random() * 6;',
'            particles.push({',
'              type: \'shard\',',
'              x: cx, y: cy,',
'              vx: Math.cos(angle) * speed,',
'              vy: Math.sin(angle) * speed - 1,',
'              rot: 0, vrot: (Math.random() - 0.5) * 0.25,',
'              size: 2 + Math.random() * 4,',
'              life: 1, decay: 0.008 + Math.random() * 0.008,',
'              color: Math.random() < 0.5 ? colA : colB',
'            });',
'          }',
'        }',
'',
'        // 冲击波环（3 层错峰）',
'        const shockwaves = [];',
'        function addShockwave(delay) {',
'          shockwaves.push({ r: 6, life: 1, delay: delay || 0 });',
'        }',
'',
'        let flash = 0;',
'',
'        // 绘制行星（简化版）',
'        function drawPlanet(x, y, r, color, glow) {',
'          const glowGrad = ctx.createRadialGradient(x, y, r * 0.3, x, y, r + glow);',
'          glowGrad.addColorStop(0, rgba(color, 0.45));',
'          glowGrad.addColorStop(0.5, rgba(color, 0.15));',
'          glowGrad.addColorStop(1, rgba(color, 0));',
'          ctx.fillStyle = glowGrad;',
'          ctx.beginPath();',
'          ctx.arc(x, y, r + glow, 0, Math.PI * 2);',
'          ctx.fill();',
'',
'          const grad = ctx.createRadialGradient(x - r * 0.35, y - r * 0.35, r * 0.1, x, y, r);',
'          grad.addColorStop(0, \'rgba(255,255,255,0.8)\');',
'          grad.addColorStop(0.35, rgba(color, 0.75));',
'          grad.addColorStop(1, rgba(color, 0.15));',
'          ctx.beginPath();',
'          ctx.arc(x, y, r, 0, Math.PI * 2);',
'          ctx.fillStyle = grad;',
'          ctx.fill();',
'        }',
'',
'        // ============ 主循环 ============',
'        function frame(now) {',
'          const elapsed = now - startTime;',
'          const t = Math.min(elapsed / DURATION, 1);',
'',
'          // 清画布 + 纯色背景',
'          ctx.clearRect(0, 0, canvas.width, canvas.height);',
'          ctx.fillStyle = \'rgba(3, 3, 15, 1)\';',
'          ctx.fillRect(0, 0, canvas.width, canvas.height);',
'',
'          // 背景星星',
'          for (let i = 0; i < bgStars.length; i++) {',
'            const s = bgStars[i];',
'            const tw = 0.6 + 0.4 * Math.sin(now * 0.003 + s.phase);',
'            ctx.globalAlpha = s.alpha * tw;',
'            ctx.fillStyle = \'#ffffff\';',
'            ctx.fillRect(s.x, s.y, s.size, s.size);',
'          }',
'          ctx.globalAlpha = 1;',
'',
'          // 阶段',
'          const APPROACH_END = 0.42;',
'          const IMPACT_T = 0.43;',
'',
'          // ======= 1. 飞行接近 =======',
'          if (t < APPROACH_END) {',
'            const at = t / APPROACH_END;',
'            const ease = at < 0.5 ? 2 * at * at : 1 - Math.pow(-2 * at + 2, 2) / 2;',
'            const p1x = -80 + (cx - (-80)) * ease;',
'            const p1y = cy;',
'            const p2x = canvas.width + 80 + (cx - (canvas.width + 80)) * ease;',
'            const p2y = cy;',
'            const glow = 14 + at * 22;',
'',
'            drawPlanet(p1x, p1y, 36, colA, glow);',
'            drawPlanet(p2x, p2y, 36, colB, glow);',
'',
'            // 两星之间的连接线，接近时变亮',
'            if (at > 0.5) {',
'              ctx.globalAlpha = (at - 0.5) * 1.2;',
'              ctx.strokeStyle = rgba(colA, 0.3);',
'              ctx.lineWidth = 1;',
'              ctx.beginPath();',
'              ctx.moveTo(p1x + 36, cy);',
'              ctx.lineTo(p2x - 36, cy);',
'              ctx.stroke();',
'              ctx.globalAlpha = 1;',
'            }',
'          }',
'',
'          // ======= 2. 撞击瞬间 =======',
'          if (t >= APPROACH_END && t < IMPACT_T) {',
'            if (!hasImpactFired) {',
'              hasImpactFired = true;',
'              spawnImpactBurst();',
'              addShockwave(0);',
'              addShockwave(0.1);',
'              addShockwave(0.2);',
'              flash = 1;',
'            }',
'            drawPlanet(cx, cy, 44, colA, 40);',
'          }',
'',
'          // ======= 3. 粒子扩散阶段 =======',
'          if (t >= IMPACT_T) {',
'            // 单循环更新 + 绘制所有粒子',
'            for (let i = particles.length - 1; i >= 0; i--) {',
'              const p = particles[i];',
'',
'              if (p.type === \'debris\') {',
'                p.x += p.vx; p.y += p.vy;',
'                p.vx *= 0.94; p.vy = p.vy * 0.94 + 0.04;',
'                p.life -= p.decay;',
'              } else if (p.type === \'sparkle\') {',
'                p.x += p.vx; p.y += p.vy;',
'                p.vx *= 0.9; p.vy *= 0.9;',
'                p.life -= p.decay;',
'              } else if (p.type === \'shard\') {',
'                p.x += p.vx; p.y += p.vy;',
'                p.vx *= 0.96; p.vy = p.vy * 0.96 + 0.15;',
'                p.rot += p.vrot;',
'                p.life -= p.decay;',
'              } else if (p.type === \'star\') {',
'                p.x += p.vx; p.y += p.vy;',
'                p.vx *= 0.985; p.vy *= 0.985;',
'                const dx = cx - p.x;',
'                const dy = cy - p.y;',
'                const dist = Math.sqrt(dx * dx + dy * dy);',
'                if (dist > 120) {',
'                  p.vx += (dx / dist) * 0.012;',
'                  p.vy += (dy / dist) * 0.012;',
'                } else if (dist < 30) {',
'                  p.vx += (Math.random() - 0.5) * 0.1;',
'                  p.vy += (Math.random() - 0.5) * 0.1;',
'                }',
'                p.life -= p.decay;',
'                p.twinkle += 0.06;',
'              }',
'',
'              if (p.life <= 0) {',
'                particles.splice(i, 1);',
'                continue;',
'              }',
'',
'              // 绘制',
'              if (p.type === \'debris\') {',
'                ctx.globalAlpha = p.life;',
'                ctx.fillStyle = rgba(p.color, p.life);',
'                ctx.fillRect(Math.round(p.x - p.size / 2), Math.round(p.y - p.size / 2), Math.round(p.size), Math.round(p.size));',
'              } else if (p.type === \'sparkle\') {',
'                ctx.globalAlpha = p.life;',
'                ctx.fillStyle = \'rgba(255,255,255,\' + p.life + \')\';',
'                ctx.fillRect(p.x - p.size, p.y - 0.5, p.size * 2, 1);',
'                ctx.fillRect(p.x - 0.5, p.y - p.size, 1, p.size * 2);',
'              } else if (p.type === \'shard\') {',
'                ctx.save();',
'                ctx.translate(p.x, p.y);',
'                ctx.rotate(p.rot);',
'                ctx.globalAlpha = p.life;',
'                ctx.fillStyle = rgba(p.color, p.life);',
'                ctx.fillRect(-p.size / 2, -p.size / 2, p.size, p.size * 0.7);',
'                ctx.restore();',
'              } else if (p.type === \'star\') {',
'                const tw = 0.5 + 0.5 * Math.sin(p.twinkle);',
'                ctx.globalAlpha = Math.max(p.life * tw, 0.25);',
'                ctx.fillStyle = rgba(p.color, p.life * tw);',
'                ctx.fillRect(Math.round(p.x - p.size / 2), Math.round(p.y - p.size / 2), Math.round(p.size), Math.round(p.size));',
'                if (tw > 0.82) {',
'                  ctx.globalAlpha = p.life * 0.4;',
'                  ctx.fillStyle = \'#ffffff\';',
'                  ctx.fillRect(Math.round(p.x - p.size * 1.5), Math.round(p.y), Math.round(p.size * 3), 1);',
'                  ctx.fillRect(Math.round(p.x), Math.round(p.y - p.size * 1.5), 1, Math.round(p.size * 3));',
'                }',
'              }',
'            }',
'            ctx.globalAlpha = 1;',
'',
'            // 冲击波环',
'            for (let i = 0; i < shockwaves.length; i++) {',
'              const s = shockwaves[i];',
'              if (s.delay > 0) {',
'                s.delay -= 1 / 60;',
'                continue;',
'              }',
'              s.r += 8;',
'              s.life -= 0.02;',
'              if (s.life > 0) {',
'                ctx.globalAlpha = s.life * 0.5;',
'                ctx.strokeStyle = rgba(i % 2 === 0 ? colA : colB, s.life * 0.5);',
'                ctx.lineWidth = 2;',
'                ctx.beginPath();',
'                ctx.arc(cx, cy, s.r, 0, Math.PI * 2);',
'                ctx.stroke();',
'              }',
'            }',
'            ctx.globalAlpha = 1;',
'',
'            // 文字切换',
'            if (t > 0.7 && collisionCaption && !collisionCaption._successShown) {',
'              collisionCaption.textContent = \'连接成功！✨\';',
'              collisionCaption._successShown = true;',
'            }',
'          }',
'',
'          // 全屏闪光衰减',
'          if (flash > 0.01) {',
'            ctx.fillStyle = \'rgba(255,255,255,\' + (flash * 0.55) + \')\';',
'            ctx.fillRect(0, 0, canvas.width, canvas.height);',
'            flash *= 0.88;',
'          }',
'',
'          // ======= 结束判定 =======',
'          if (t < 1) {',
'            animId = requestAnimationFrame(frame);',
'          } else {',
'            if (collisionCaption) collisionCaption.textContent = \'连接成功！✨\';',
'            setTimeout(function () {',
'              if (animId) cancelAnimationFrame(animId);',
'              collisionOverlay.classList.remove(\'active\');',
'              collisionOverlay.setAttribute(\'aria-hidden\', \'true\');',
'              collisionPlaying = false;',
'              resolve();',
'            }, 600);',
'          }',
'        }',
'',
'        // 启动（带异常保护）',
'        try {',
'          requestAnimationFrame(frame);',
'        } catch (e) {',
'          collisionOverlay.classList.remove(\'active\');',
'          collisionPlaying = false;',
'          resolve();',
'        }',
'      });',
'    }'
];

var before = lines.slice(0, startIdx);
var after = lines.slice(endIdx + 1);
var result = before.concat(newFunc).concat(after);

// 检测原文件换行符
var lineBreak = content.indexOf('\r\n') !== -1 ? '\r\n' : '\n';
fs.writeFileSync(path, result.join(lineBreak), 'utf8');

console.log('替换完成！共 ' + result.length + ' 行');
console.log('新函数签名: ' + result[startIdx]);
